name: ellipsize
version: 0.1.0
author: W. Brian Gourlie
description: Truncates and adds ellipses to multiline text that overflows its container.
homepage: https://github.com/bgourlie/ellipsize
environment:
  sdk: '>=0.3.7'

#dependencies:
#  js: any
#  unittest: any