name: ellipsize
version: 0.2.2
author: W. Brian Gourlie <bgourlie@gmail.com>
description: Truncates and adds ellipses to multiline text that overflows its container.
homepage: https://github.com/bgourlie/ellipsize
environment:
  sdk: '>=0.3.7'
dependencies:
  browser: any

#dependencies:
#  js: any
#  unittest: any